# Generated by Django 5.2.6 on 2025-09-10 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(verbose_name='所属帖子ID')),
                ('user_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='评论者标识')),
                ('content', models.TextField(max_length=1000, verbose_name='评论内容')),
                ('parent_comment_id', models.IntegerField(default=0, verbose_name='父评论ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'interview_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_user_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='接收通知用户标识')),
                ('sender_user_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='发送通知用户标识')),
                ('notification_type', models.CharField(choices=[('reply', '回复'), ('system', '系统通知')], max_length=10, verbose_name='通知类型')),
                ('message', models.CharField(max_length=200, verbose_name='通知消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('post_id', models.IntegerField(blank=True, null=True, verbose_name='关联帖子ID')),
                ('comment_id', models.IntegerField(blank=True, null=True, verbose_name='关联评论ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知时间')),
            ],
            options={
                'db_table': 'interview_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('user_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='用户标识')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论次数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'interview_post',
                'ordering': ['-is_sticky', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='学生姓名')),
                ('number', models.CharField(max_length=255, verbose_name='学生学号')),
                ('good_at', models.TextField(blank=True, null=True, verbose_name='擅长领域')),
                ('grade', models.CharField(max_length=255, null=True, verbose_name='年级')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='申请理由')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='管理员评分')),
                ('book_time', models.DateTimeField(blank=True, null=True, verbose_name='申请时间')),
                ('phone_number', models.CharField(max_length=255, null=True, verbose_name='联系电话')),
                ('gaokao_math', models.IntegerField(verbose_name='高考数学成绩')),
                ('gaokao_english', models.IntegerField(verbose_name='高考英语成绩')),
                ('follow_direction', models.CharField(max_length=255, verbose_name='发展方向')),
                ('future', models.CharField(max_length=255, verbose_name='未来规划')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生申请表',
                'verbose_name_plural': '学生申请表',
                'db_table': 'book_user',
            },
        ),
    ]
