# Generated by Django 5.2.6 on 2025-09-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='项目经历'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='major',
            field=models.CharField(default='未填写', max_length=255, verbose_name='专业班级'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='other_lab',
            field=models.CharField(default='未填写', max_length=255, verbose_name='其他实验室报名情况'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='book_time',
            field=models.DateTimeField(default='2025-09-16', verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='grade',
            field=models.CharField(default='未填写', max_length=255, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='name',
            field=models.CharField(default='未填写', max_length=255, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='phone_number',
            field=models.CharField(default='未填写', max_length=255, verbose_name='联系电话'),
        ),
    ]
